AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Construccion de aplicacion para postulacion principal

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  PetStoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cl.mayne.productos.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: ./spring-lambda-productos
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      FunctionUrlConfig:
        AuthType: NONE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductosTable
      Environment:
        Variables:
          TABLE_NAME: 'productos_dev'
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'
            
  ProductosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: productos_dev
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  SpringBootPetStoreApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: PruebaPrincipalApi
